language: erlang

otp_release:
  - 21.3
  - 20.3
  - 19.3
  - 18.3
  - 17.5
before_script: kerl list installations
script:
  - make test
  - make dialyzer
branches:
  only:
  - master
cache:
  directories:
    - _build
